redis:
  addr: "localhost:6379"
  password: "jayleonc"

db:
  src:
    dsn: "root:jayleonc@tcp(localhost:3306)/webook"
  dst:
    dsn: "root:jayleonc@tcp(localhost:3306)/webook_intr"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    etcdAddr: "localhost:2379"
    port: 8090
    name: "interactive"