apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-pvc
spec:
  storageClassName: webook
  accessModes: # 访问模式，控制能不能被多个 Pod 读写
    - ReadWriteOnce # 只能被一个 Pod 读写
  resources: # 需要什么资源
    requests:
      storage: 1Gi