apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-pv
spec:
  storageClassName: webook
  capacity:
    storage: 1Gi # 存储容量
  accessModes:
    - ReadWriteOnce # 本 PV 支持的访问方式
  hostPath:
    path: "/mnt/data" # 本 PV 的根目录