wrk.method = "GET"
wrk.headers["Content-Type"] = "application/json"
wrk.headers["User-Agent"] = "PostmanRuntime/7.32.3"
wrk.headers["Authorization"] = "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDg1MDUzOTgsIlVpZCI6MSwiU3NpZCI6IjBmODY4NjhkLTRkOWYtNDU3Yy1hZTc0LWM1OWNiYTE4M2U0MyIsIkVtYWlsIjoiSmF5bGVvbmNAMTYzLmNvbSIsIlBob25lIjoiIiwiVXNlckFnZW50IjoiUG9zdG1hblJ1bnRpbWUvNy4zNi4zIn0.oLy4-YRdmINRZCwp0xAIW0fWBMBmAvbNnWO_dxvRN8cMpO0x_e_-c8xh3Pdc3lLosnRY4X8nTCzn8SLhYSNxKA"
wrk.path = "/articles/pub/top/10"