wrk.method = "GET"
wrk.headers["Content-Type"] = "application/json"
wrk.headers["User-Agent"] = "PostmanRuntime/7.32.3"
wrk.headers["Authorization"] = "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDg5NTMxMDksIlVpZCI6MSwiU3NpZCI6IjEwM2IyNTBmLTViYzktNDNiYS1hY2U1LTAwMzQyZGVhMjFkNCIsIkVtYWlsIjoiSmF5bGVvbmNAMTYzLmNvbSIsIlBob25lIjoiIiwiVXNlckFnZW50IjoiUG9zdG1hblJ1bnRpbWUvNy4zNi4zIn0.p0pmUdd3AbZP2FTkRDu3Kb_knXeRn03pxtd9FfF2eMLibwcF5bG58eCYMGUxlIYoq5S4O865_n6ZpPUhB430ow"
wrk.path = "/articles/pub/top/1"