redis:
  addr: "localhost:6379"
  password: "jayleonc"

db:
  dsn: "root:jayleonc@tcp(localhost:3306)/geektime"

kafka:
  addrs:
    - "localhost:9094"


grpc:
  client:
    intr:
      addr: "localhost:8090"
      threshold: 100