redis:
  addr: "localhost:6379"
  password: "jayleonc"

db:
  dsn: "root:jayleonc@tcp(localhost:3306)/webook"

kafka:
  addrs:
    - "localhost:9094"

etcd:
  addrs:
    - "localhost:2379"

grpc:
  client:
    intr:
      addr: "etcd:///service/interactive"