// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/jayleonc/geektime-go/webook/interactive/events"
	"github.com/jayleonc/geektime-go/webook/interactive/events/prometheus"
	"github.com/jayleonc/geektime-go/webook/interactive/grpc"
	"github.com/jayleonc/geektime-go/webook/interactive/ioc"
	"github.com/jayleonc/geektime-go/webook/interactive/repository"
	"github.com/jayleonc/geektime-go/webook/interactive/repository/cache"
	"github.com/jayleonc/geektime-go/webook/interactive/repository/dao"
	"github.com/jayleonc/geektime-go/webook/interactive/service"
)

// Injectors from wire.go:

func InitApp() *App {
	srcDB := ioc.InitSrcDB()
	dstDB := ioc.InitDstDB()
	logger := ioc.InitLogger()
	doubleWritePool := ioc.InitDoubleWritePool(srcDB, dstDB, logger)
	db := ioc.InitBizDB(doubleWritePool)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewInteractiveRedisCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache)
	client := ioc.InitKafka()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(interactiveRepository, client)
	interactiveReadEventConsumerWithMetrics := prometheus.NewInteractiveReadEventConsumerWithMetrics(interactiveReadEventConsumer)
	consumer := ioc.InitFixerConsumer(client, logger, srcDB, dstDB)
	v := ioc.InitConsumers(interactiveReadEventConsumerWithMetrics, consumer)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.NewGrpcxServer(interactiveServiceServer, logger)
	syncProducer := ioc.NewSyncProducer(client)
	producer := ioc.InitInteractiveProducer(syncProducer)
	ginxServer := ioc.InitGinxServer(logger, srcDB, dstDB, doubleWritePool, producer)
	app := &App{
		Consumers:   v,
		Server:      server,
		AdminServer: ginxServer,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitSrcDB, ioc.InitDstDB, ioc.InitDoubleWritePool, ioc.InitBizDB, ioc.InitLogger, ioc.InitKafka, ioc.NewSyncProducer, ioc.InitRedis)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewInteractiveRedisCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)
